site_name: Platform Development Playbook
repo_url: https://github.com/amdigital-co-uk/docs-playbook
repo_name: GitHub
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  logo: assets/images/AM no tag.png
  name: material
  favicon: assets/images/android-chrome-192x192.png 
  custom_dir: mkdocs-overrides
  features:
    - header.autohide
    - navigation.instant    
    - navigation.tracking
    - navigation.indexes
  plugins:
    - search
    - mermaid2
    - git-revision-date-localized
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: AM      
      toggle:
          icon: material/eye-outline
          name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye
        name: Switch to light mode
        theme:
  icon:
    admonition:
      quote: octicons/book-16
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/adam-matthew-digital-ltd/mycompany/
    - icon: octicons/person-add-16
      link: https://careers.amdigital.co.uk/departments/platform-development
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tasklist:
      custom_checkbox: true
- pymdownx.tabbed:
      alternate_style: true
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- abbr
- attr_list
- md_in_html
- toc:
      permalink: true      
      title: On this page
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg