site_name: Platform Development Playbook
repo_url: https://github.com/amdigital-co-uk/amdigital-co-uk.github.io/
repo_name: GitHub
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  logo: assets/logo.jfif
  name: material
  favicon: assets/favicon.ico
  features:
    - header.autohide
    - navigation.instant    
    - navigation.tracking
  plugins:
    - search
    - mermaid2
    - git-revision-date-localized
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: AM      
      toggle:
          icon: material/eye-outline
          name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/adam-matthew-digital-ltd/mycompany/
    - icon: octicons/person-add-16
      link: https://careers.amdigital.co.uk/departments/platform-development
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- abbr
- attr_list
- md_in_html
- toc:
      permalink: true      
      title: On this page
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
