name: Deploy Site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  documentation:
    name: Build site
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install MKdocs and theme
        run: |
          pip install mkdocs-material
      
      - name: Deploy MKdocs site
        run: |
          mkdocs build
          mv site python-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'am-playbook-test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A059A3EF380546C0BFA64A5CCE97B088 }}